version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - postgres
      - redis
    command: /start
    networks:
      -  notes-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - notes_local_postgres_data:/var/lib/postgresql/data
      - notes_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres
    networks:
      -  notes-api
    platform: linux/amd64


  redis:
    image: redis:7-alpine
    platform: linux/arm64
    networks:
      -  notes-api

  

  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      -  notes-api

networks:
   notes-api:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  notes_local_postgres_data: {}
  notes_local_postgres_data_backups: {}
